/**
 * Country names, as codes.
 *
 * The pricing rules read an ISO code: `NG` is naira, `GB` is sterling, a list
 * of European codes is euro, and anything unrecognised is dollars. That last
 * clause is why this file exists.
 *
 * Registrations taken before the country became a selector hold whatever was
 * typed — "Nigeria", "France", "Ghana". Those are not codes, so they fell
 * through to "unrecognised", and a Nigerian was quoted in dollars for an event
 * priced in naira. Normalising the name first is what stops that.
 *
 * Aliases are included for the names people actually write: UK and England for
 * GB, USA and America for US, Ivory Coast for CI.
 */

const NAME_TO_CODE = new Map<string, string>([
  ['albania', 'AL'],
  ['algeria', 'DZ'],
  ['america', 'US'],
  ['andorra', 'AD'],
  ['angola', 'AO'],
  ['argentina', 'AR'],
  ['armenia', 'AM'],
  ['australia', 'AU'],
  ['austria', 'AT'],
  ['azerbaijan', 'AZ'],
  ['bahamas', 'BS'],
  ['bahrain', 'BH'],
  ['bangladesh', 'BD'],
  ['barbados', 'BB'],
  ['belarus', 'BY'],
  ['belgium', 'BE'],
  ['benin', 'BJ'],
  ['bolivia', 'BO'],
  ['bosnia and herzegovina', 'BA'],
  ['botswana', 'BW'],
  ['brazil', 'BR'],
  ['britain', 'GB'],
  ['bulgaria', 'BG'],
  ['burkina faso', 'BF'],
  ['burundi', 'BI'],
  ['cabo verde', 'CV'],
  ['cameroon', 'CM'],
  ['canada', 'CA'],
  ['cape verde', 'CV'],
  ['central african republic', 'CF'],
  ['chad', 'TD'],
  ['chile', 'CL'],
  ['china', 'CN'],
  ['colombia', 'CO'],
  ['comoros', 'KM'],
  ['congo', 'CG'],
  ['congo (drc)', 'CD'],
  ['costa rica', 'CR'],
  ["cote d'ivoire", 'CI'],
  ['croatia', 'HR'],
  ['cuba', 'CU'],
  ['cyprus', 'CY'],
  ['czech republic', 'CZ'],
  ['czechia', 'CZ'],
  ['democratic republic of the congo', 'CD'],
  ['denmark', 'DK'],
  ['djibouti', 'DJ'],
  ['dominican republic', 'DO'],
  ['dr congo', 'CD'],
  ['ecuador', 'EC'],
  ['egypt', 'EG'],
  ['el salvador', 'SV'],
  ['england', 'GB'],
  ['equatorial guinea', 'GQ'],
  ['eritrea', 'ER'],
  ['estonia', 'EE'],
  ['eswatini', 'SZ'],
  ['ethiopia', 'ET'],
  ['faroe islands', 'FO'],
  ['fiji', 'FJ'],
  ['finland', 'FI'],
  ['france', 'FR'],
  ['gabon', 'GA'],
  ['gambia', 'GM'],
  ['georgia', 'GE'],
  ['germany', 'DE'],
  ['ghana', 'GH'],
  ['gibraltar', 'GI'],
  ['great britain', 'GB'],
  ['greece', 'GR'],
  ['guatemala', 'GT'],
  ['guernsey', 'GG'],
  ['guinea', 'GN'],
  ['guinea-bissau', 'GW'],
  ['haiti', 'HT'],
  ['holland', 'NL'],
  ['holy see', 'VA'],
  ['honduras', 'HN'],
  ['hong kong', 'HK'],
  ['hungary', 'HU'],
  ['iceland', 'IS'],
  ['india', 'IN'],
  ['indonesia', 'ID'],
  ['iran', 'IR'],
  ['iraq', 'IQ'],
  ['ireland', 'IE'],
  ['isle of man', 'IM'],
  ['israel', 'IL'],
  ['italy', 'IT'],
  ['ivory coast', 'CI'],
  ['jamaica', 'JM'],
  ['japan', 'JP'],
  ['jersey', 'JE'],
  ['jordan', 'JO'],
  ['kazakhstan', 'KZ'],
  ['kenya', 'KE'],
  ['korea', 'KR'],
  ['kosovo', 'XK'],
  ['kuwait', 'KW'],
  ['latvia', 'LV'],
  ['lebanon', 'LB'],
  ['lesotho', 'LS'],
  ['liberia', 'LR'],
  ['libya', 'LY'],
  ['liechtenstein', 'LI'],
  ['lithuania', 'LT'],
  ['luxembourg', 'LU'],
  ['macedonia', 'MK'],
  ['madagascar', 'MG'],
  ['malawi', 'MW'],
  ['malaysia', 'MY'],
  ['mali', 'ML'],
  ['malta', 'MT'],
  ['mauritania', 'MR'],
  ['mauritius', 'MU'],
  ['mexico', 'MX'],
  ['moldova', 'MD'],
  ['monaco', 'MC'],
  ['montenegro', 'ME'],
  ['morocco', 'MA'],
  ['mozambique', 'MZ'],
  ['namibia', 'NA'],
  ['nepal', 'NP'],
  ['netherlands', 'NL'],
  ['new zealand', 'NZ'],
  ['nicaragua', 'NI'],
  ['niger', 'NE'],
  ['nigeria', 'NG'],
  ['north macedonia', 'MK'],
  ['northern ireland', 'GB'],
  ['norway', 'NO'],
  ['oman', 'OM'],
  ['pakistan', 'PK'],
  ['panama', 'PA'],
  ['papua new guinea', 'PG'],
  ['paraguay', 'PY'],
  ['peru', 'PE'],
  ['philippines', 'PH'],
  ['poland', 'PL'],
  ['portugal', 'PT'],
  ['qatar', 'QA'],
  ['republic of korea', 'KR'],
  ['romania', 'RO'],
  ['russia', 'RU'],
  ['rwanda', 'RW'],
  ['san marino', 'SM'],
  ['sao tome and principe', 'ST'],
  ['saudi arabia', 'SA'],
  ['scotland', 'GB'],
  ['senegal', 'SN'],
  ['serbia', 'RS'],
  ['seychelles', 'SC'],
  ['sierra leone', 'SL'],
  ['singapore', 'SG'],
  ['slovakia', 'SK'],
  ['slovenia', 'SI'],
  ['somalia', 'SO'],
  ['south africa', 'ZA'],
  ['south korea', 'KR'],
  ['south sudan', 'SS'],
  ['spain', 'ES'],
  ['sri lanka', 'LK'],
  ['sudan', 'SD'],
  ['swaziland', 'SZ'],
  ['sweden', 'SE'],
  ['switzerland', 'CH'],
  ['syria', 'SY'],
  ['taiwan', 'TW'],
  ['tanzania', 'TZ'],
  ['thailand', 'TH'],
  ['togo', 'TG'],
  ['trinidad and tobago', 'TT'],
  ['tunisia', 'TN'],
  ['turkey', 'TR'],
  ['turkiye', 'TR'],
  ['uae', 'AE'],
  ['uganda', 'UG'],
  ['uk', 'GB'],
  ['ukraine', 'UA'],
  ['united arab emirates', 'AE'],
  ['united kingdom', 'GB'],
  ['united states', 'US'],
  ['united states of america', 'US'],
  ['uruguay', 'UY'],
  ['usa', 'US'],
  ['uzbekistan', 'UZ'],
  ['vatican city', 'VA'],
  ['venezuela', 'VE'],
  ['vietnam', 'VN'],
  ['wales', 'GB'],
  ['yemen', 'YE'],
  ['zambia', 'ZM'],
  ['zimbabwe', 'ZW'],
]);

/**
 * A country as a two-letter code, from either a code or a name.
 *
 * Returns the input uppercased when it is already two letters, so an unknown
 * code still reaches the pricing rules and is treated as somewhere abroad
 * rather than as nothing at all.
 */
export function countryToCode(value: string): string {
  const trimmed = String(value ?? '').trim();
  if (trimmed === '') return '';

  // The table is consulted before the two-letter shortcut, because some of the
  // things people write are two letters and are *not* the code: "UK" is the
  // name everyone uses and `GB` is the code. Treating it as a code because it
  // was the right length is how the United Kingdom priced as somewhere
  // unrecognised.
  const named = NAME_TO_CODE.get(trimmed.toLowerCase());
  if (named !== undefined) return named;

  return trimmed.toUpperCase();
}
